version = 1
exclude_patterns = [
  ".github/**",
  "ideconfig/**",
  ".gitignore",
  "*.md",
  "*.py",
  "*.toml"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

